server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://101.35.186.195:3306/thpass?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Kitsune
    password: YkEQPddRRZqa2jdR

    hikari:
      maximum-pool-size: 100
      auto-commit: true
      minimum-idle: 10
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: MySQL

variables:
  auth_URL: /oauth2/consent
