server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/th_passport?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    hikari:
      maximum-pool-size: 100
      auto-commit: true
      minimum-idle: 10
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: MySQL

variables:
  auth_URL: /oauth2/consent
